name: Running when pushing to main
on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Setup git
        run: |
          GIT_URL="https://alk-sdavid:${GITHUB_TOKEN}@github.com/alk-sdavid/conventional-commits.git"
          git config --global user.email 50570955+alk-sdavid@users.noreply.github.com
          git config --global user.name "Sébastien David (seb)"
          git remote add ci $GIT_URL
        env:
          GITHUB_TOKEN: ${{ secrets.SEB_GITHUB_TOKEN }}
      - name: Patch package
        run: npm version patch --no-git-tag-version
      - name: Github release
        run: |
          VERSION=$(node -p "require('./package.json').version")
          TAG=v$VERSION
          gh release view $TAG || EXIT_STATUS=$?
          if [[ $EXIT_STATUS -eq 0 ]]; then
            gh release edit $TAG --title "$VERSION" --generate-notes --draft
          else
            git tag --force $TAG
            git push --force ci $TAG
            gh release create $TAG --title "$VERSION" --generate-notes --draft
          fi
          RELEASE_BODY=$(gh release view $TAG --json body --jq .body)
          CHANGELOG=$(cat CHANGELOG.md)
          printf "# $VERSION\n\n$RELEASE_BODY\n\n$CHANGELOG" > CHANGELOG.md
          git add package.json package-lock.json CHANGELOG.md
          git commit --message "chore(release): $VERSION [ci skip]"
          git push ci main
          git tag --force $TAG
          git push --force ci $TAG
          gh release edit $TAG --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.SEB_GITHUB_TOKEN }}

